Repository WindowsSystemAdmin/research, pull requests merged in 2023-06, with the labels that each got.

#26 Style updated
  style.css
Labels: Documentation, Enhancement, Assigned, Positive review, Medium

#27 Update README.markdown
  README.markdown
Labels: Documentation, Enhancement, Assigned, Positive review, Low

#28 Additions and fixes
  php/ResearchResources.php
Labels: Documentation, Enhancement, Needs review, Critical

#30 Navigation improvements to site
  php/ResearchResources.php
Labels: Enhancement, Assigned, Positive review, Medium
